- hosts: bootstrapmaster
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

- hosts: worker_nodes
  tasks:
    - name: activate ip forwarding
      shell: echo 1 >> /proc/sys/net/bridge/bridge-nf-call-iptables
    - name: set join command
      set_fact:
        join_command: "{{ hostvars[groups['bootstrapmaster'][0]]['join_command_raw'].stdout_lines[0] }}"
    - name: ensure binaries for current kubernetes version "{{ k8s_version }}" are installed
      yum:
        name: "{{ packages }}"
        allow_downgrade: yes
      vars:
        packages:
        - kubelet-{{ k8s_version }}-0
        - kubectl-{{ k8s_version }}-0
        - kubeadm-{{ k8s_version }}-0
    - name: join new worker node
      shell: "{{ join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

- hosts: bootstrapmaster
  tasks: 
    - name: add worker lable to the worker nodes
      shell: "kubectl label nodes --overwrite=true {{ hostvars[item]['ansible_hostname'] }} node-role.kubernetes.io/worker=worker"
      with_items:
        - "{{ groups['worker_nodes'] }}"
