- hosts: bootstrapmaster
  tasks:
    - name: upload certs with encryption key {{ encrypt_key }}
      shell: kubeadm init phase upload-certs --upload-certs --certificate-key "{{ encrypt_key }}"
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

- hosts: new_control_plane_nodes
  tasks:
    - name: activate ip forwarding
      shell: echo 1 >> /proc/sys/net/bridge/bridge-nf-call-iptables
    - name: set join command
      set_fact:
        join_command: "{{ hostvars[groups['bootstrapmaster'][0]]['join_command_raw'].stdout_lines[0] }}"
    - name: ensure binaries for current kubernetes version "{{ k8s_version }}" are installed
      yum:
        name: "{{ packages }}"
        allow_downgrade: yes
      vars:
        packages:
        - kubelet-{{ k8s_version }}-0
        - kubectl-{{ k8s_version }}-0
        - kubeadm-{{ k8s_version }}-0
    - name: join new control plane
      shell: "{{ join_command }} --control-plane --certificate-key {{ encrypt_key }}"
      args:
        chdir: $HOME
        creates: node_joined.txt
    - name: move kubeconfig to HOME
      shell: /bin/mkdir -p $HOME/.kube && /bin/cp /etc/kubernetes/admin.conf $HOME/.kube/config && /bin/chown $(id -u):$(id -g) $HOME/.kube/config
