- hosts: all
  tasks:
    - name: install already downloaded kubeadm {{ k8s_version }}
      yum:
        name: kubeadm-{{ k8s_version }}-0
        allow_downgrade: yes
- hosts: bootstrapmaster
  tasks:
    - name: upgrade control plane to {{ k8s_version }}
      shell: kubeadm upgrade apply v{{ k8s_version }} -y

- hosts: other_control_plane_nodes
  tasks:
    - name: upgrade control plane to {{ k8s_version }}
      shell: kubeadm upgrade node

- hosts: all
  tasks:
    - name: install binaries for kubernetes version "{{ k8s_version }}"
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - kubelet-{{ k8s_version }}-0
        - kubectl-{{ k8s_version }}-0
    - name: restart kubelet
      systemd:
        name: kubelet
        state: restarted
        daemon_reload: yes