kind: Deployment
apiVersion: apps/v1
metadata:
  name: core-dump
  labels:
    app: core-dump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-dump
  template:
    metadata:
      labels:
        app: core-dump
    spec:
      containers:
      - name: core-dump
        image: sherlockapps/test:coredump 
        imagePullPolicy: Always
