apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testsets.sherlock
spec:
  group: sherlock
  names:
    kind: TestSet
    listKind: TestSetList
    plural: testsets
    singular: testset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: TestSet is the Schema for the testsets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TestSetSpec defines the desired state of TestSet
          type: object
        status:
          description: TestSetStatus defines the observed state of TestSet
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
